#ifndef LIBNEUROSUITE_GLOBAL_H
#define LIBNEUROSUITE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBNEUROSUITE_LIBRARY)
#  define LIBNEUROSUITESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBNEUROSUITESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBNEUROSUITE_GLOBAL_H
